### ISSUE TITLE
create a window and open it hidden

### ISSUE THREAD

**Issue by f0lmer** [tamkeen-tms/electron-window-manager#79]
hi so im creating a program and i'm looking for a way to create a browser window and open it without showing it yet. so its basically launching headless. electron uses show: false. but i cant seem to get that to work with this. anyone that has a suggestion so one more time in steps.
'create a window and launch it (without showing)'
'show the window' (different button in my program)

thanks in advance

**Comment by f0lmer** [comment]
got an alternative working

**Comment by rexn8r** [comment]
hi @f0lmer 

how did you manage to implement it?

i am looking to implement similar way. show/hide window based on button click.

thanks
rex
